---
- name: Apply EDA Configuration-as-code
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/eda_secrets.yml

  tasks:
    - name: Include EDA configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: eda

    - name: Call dispatch role for EDA configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...