---
- name: Apply Platform Configuration-as-code
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/platform_secrets.yml

  tasks:
    - name: Include Platform (Gateway) configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: platform

    - name: Call dispatch role for Platform configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...